package boletin22;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author ldizbarros
 */
public class Exercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio1
     */
    public Exercicio1() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jlEtiqueta = new javax.swing.JLabel();
        jlEtiquetaNombre = new javax.swing.JLabel();
        jlEtiquetaNombreCompleto = new javax.swing.JLabel();
        jlEtiquetaID = new javax.swing.JLabel();
        jlEtiquetaGrupo = new javax.swing.JLabel();
        jlEtiquetaHomeDirectory = new javax.swing.JLabel();
        jlEtiquetaLoginShell = new javax.swing.JLabel();
        jlEtiquetaPassword = new javax.swing.JLabel();
        jlEtiquetaConfirm = new javax.swing.JLabel();
        jSeparador = new javax.swing.JSeparator();
        bCancel = new javax.swing.JButton();
        bOK = new javax.swing.JButton();
        jtfNombre = new javax.swing.JTextField();
        jtfUserID = new javax.swing.JTextField();
        jtfNombreCompleto = new javax.swing.JTextField();
        jtfHomeDirectory = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jpfPassword1 = new javax.swing.JPasswordField();
        jcbGroup = new javax.swing.JComboBox<>();
        jcbLoginShell = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User...");
        setIconImage(getIconImage());

        panel.setBackground(java.awt.SystemColor.window);

        jlEtiqueta.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiqueta.setText("Create a bew user");

        jlEtiquetaNombre.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaNombre.setText("User Name:");

        jlEtiquetaNombreCompleto.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaNombreCompleto.setText("Full Name:");

        jlEtiquetaID.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaID.setText("User ID:");

        jlEtiquetaGrupo.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaGrupo.setText("Group:");

        jlEtiquetaHomeDirectory.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaHomeDirectory.setText("Home Directory:");

        jlEtiquetaLoginShell.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaLoginShell.setText("Login Shell:");

        jlEtiquetaPassword.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaPassword.setText("Password:");

        jlEtiquetaConfirm.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jlEtiquetaConfirm.setText("Confirm:");

        jSeparador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bCancel.setBackground(java.awt.SystemColor.window);
        bCancel.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        bCancel.setText("Cancel");
        bCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bOK.setBackground(java.awt.SystemColor.window);
        bOK.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        bOK.setText("OK");
        bOK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfUserID.setEditable(false);
        jtfUserID.setText("(automatic)");

        jtfHomeDirectory.setEditable(false);
        jtfHomeDirectory.setText("(automatic)");

        jcbGroup.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jcbGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff", "Item 2", "Item 3", "Item 4" }));

        jcbLoginShell.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jcbLoginShell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "/bin/bash", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparador)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEtiqueta)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEtiquetaHomeDirectory)
                                    .addComponent(jlEtiquetaPassword)
                                    .addComponent(jlEtiquetaConfirm)
                                    .addComponent(jlEtiquetaLoginShell))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfHomeDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(jpfPassword)
                                    .addComponent(jpfPassword1)
                                    .addComponent(jcbLoginShell, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(jlEtiquetaNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(jlEtiquetaNombreCompleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEtiquetaID)
                                    .addComponent(jlEtiquetaGrupo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEtiqueta)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlEtiquetaNombre)
                                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jlEtiquetaNombreCompleto))
                                    .addComponent(jtfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jlEtiquetaID)
                                .addGap(18, 18, 18)
                                .addComponent(jlEtiquetaGrupo)
                                .addGap(125, 125, 125))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jtfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfHomeDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlEtiquetaHomeDirectory))
                                .addGap(8, 8, 8)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbLoginShell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlEtiquetaLoginShell))
                                .addGap(45, 45, 45))
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlEtiquetaPassword)))
                        .addGap(35, 35, 35))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlEtiquetaConfirm)))
                .addGap(18, 18, 18)
                .addComponent(jSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio1().setVisible(true);
            }
        });
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("boletin22/iconos/user.png"));
        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private javax.swing.JSeparator jSeparador;
    private javax.swing.JComboBox<String> jcbGroup;
    private javax.swing.JComboBox<String> jcbLoginShell;
    private javax.swing.JLabel jlEtiqueta;
    private javax.swing.JLabel jlEtiquetaConfirm;
    private javax.swing.JLabel jlEtiquetaGrupo;
    private javax.swing.JLabel jlEtiquetaHomeDirectory;
    private javax.swing.JLabel jlEtiquetaID;
    private javax.swing.JLabel jlEtiquetaLoginShell;
    private javax.swing.JLabel jlEtiquetaNombre;
    private javax.swing.JLabel jlEtiquetaNombreCompleto;
    private javax.swing.JLabel jlEtiquetaPassword;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfPassword1;
    private javax.swing.JTextField jtfHomeDirectory;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombreCompleto;
    private javax.swing.JTextField jtfUserID;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
